import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';





if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));


/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//   "aws_project_region": "ap-south-1",
//   "aws_dynamodb_all_tables_region": "ap-south-1",
//   "aws_dynamodb_table_schemas": [
//       {
//           "tableName": "customer-dev",
//           "region": "ap-south-1"
//       }
//   ],
//   "aws_cloud_logic_custom": [
//       {
//           "name": "apiddb8239b",
//           "endpoint": "https://jb86nnub79.execute-api.ap-south-1.amazonaws.com/dev",
//           "region": "ap-south-1"
//       }
//   ]
// };


// export default awsmobile;
